version: "3"
services:
  dev:
    build: .
    volumes:
      - .:/src
      - ./.tmp/go/pkg:/go/pkg
      - ./.tmp/go/cache:/.cache
      - ./.tmp/mmake:/usr/local/include/github.com
    environment:
      - PG_SERVICE=postgres
      - PG_USER=indebted
      - PG_PWD=indebted
    depends_on:
      - postgres

  postgres:
    image: postgres:9.6-alpine
    command: postgres -c log_statement=all
    environment:
      POSTGRES_USER: indebted
      POSTGRES_PASSWORD: indebted
      POSTGRES_DB: indebted
