version: "3.1"
services:
  test:
    build:
      context: .
      dockerfile: ./images/test.Dockerfile
    volumes:
      - ../:/src
    working_dir: /src
    depends_on:
      - postgres

  postgres:
    image: postgres:9.6-alpine
    command: postgres -c log_statement=all
    environment:
      POSTGRES_USER: indebted
      POSTGRES_PASSWORD: indebted
      POSTGRES_DB: indebted
    ports:
      - 5432:5432
