steps:
  - name: check fmt
    command: make check-fmt
    plugins:
      - docker-compose#v3.1.0:
          run: golang
          config: .buildkite/docker-compose.yml

  - name: lint
    command: make lint
    plugins:
      - docker-compose#v3.1.0:
          run: golint
          config: .buildkite/docker-compose.yml

  - name: test
    command:
      - dockerize -wait tcp://postgres:5432 -timeout 60s
      - POSTGRES_HOST=postgres make db.reset
      - make test
    plugins:
      - docker-compose#v3.1.0:
          run: test
          config: .buildkite/docker-compose.yml
