steps:
  - name: test
    command:
      - make check-fmt
      - make lint
      - dockerize -wait tcp://postgres:5432 -timeout 60s
      - DB_BASE_URL=postgres://indebted:indebted@postgres make db.reset test
    plugins:
      - docker#v3.3.0:
          image: indebted-test
          network: indebted-net
